# work-chart/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: work
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.DATABASE_PASSWORD | required "DATABASE_PASSWORD is required" | b64enc }}
  DATABASE_USER: {{ .Values.DATABASE_USER | required "DATABASE_USER is required" | b64enc }}
  DATABASE_URL: {{ .Values.DATABASE_URL | required "DATABASE_URL is required" | b64enc }}